#!/bin/bash
#
#   Nagios Check for Conditions met in Elasticsearch Watcher History
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

PROGNAME=`basename $0`
VERSION="Version 0.2"
AUTHOR="Nobody @ QXIP BV"

ST_OK=0
ST_WR=1
ST_CR=2
ST_UK=3

epoch=`date +%s`
hostname="localhost"
port=9200
status_page=".watch_history*/_count"
query='{"query": {"filtered":{"query":{"query_string":{"query":"*"}},"filter":{"range": {"@timestamp": {"gt": "now-5m"}} }} }}'
query_string="*"
timefield="@timestamp"
timerange="5m"

build_query() {
    query='{"query": {"filtered":{"query":{"query_string":{"query":"*"}},"filter":{"range": {"@timestamp": {"gt": "now-5m"}} }} }}'
    query="${query/5m/$timerange}"
    query="${query/@timestamp/$timefield}"
    query="${query/\*/$query_string}"
}

print_version() {
    echo "$VERSION $AUTHOR"
}

print_help() {
    print_version $PROGNAME $VERSION
    echo ""
    echo "$PROGNAME is a Nagios plugin to check the status of elasticsearch Watcher history."
    echo "It also parses the status page to get a few useful variables out, and return"
    echo "them in the output."
    echo ""
    echo "$PROGNAME -H localhost -P 9200 -o /tmp"
    echo ""
    echo "Options:"
    echo "  -H/--hostname"
    echo "     Defines the hostname. Default is: localhost"
    echo "  -P/--port"
    echo "     Defines the port. Default is: 9200"
    echo "  -A/--auth"
    echo "     Defines the HTTP authentication. Default is: none"
    echo "  -L/--last"
    echo "     Specifies the timerange to search (ie: 5m)."
    echo "     Default is: /tmp"
    exit $ST_UK
}

while test -n "$1"; do
    case "$1" in
        -help|-h)
            print_help
            exit $ST_UK
            ;;
        --version|-v)
            print_version $PROGNAME $VERSION
            exit $ST_UK
            ;;
        --hostname|-H)
            hostname=$2
            shift
            ;;
        --port|-P)
            port=$2
            shift
            ;;
        --auth|-A)
            http_auth=$2
            shift
            ;;
        --last|-L)
            timerange=$2
            shift
            ;;
        --ts|-T)
            timefield=$2
            shift
            ;;
        --query|-Q)
            query_string=$2
            shift
            ;;
        *)
        echo "Unknown argument: $1"
        print_help
        exit $ST_UK
        ;;
    esac
    shift
    build_query
done

get_status() {

    command="curl -XGET -q -s $hostname:$port/$status_page -d '$query'"
    if [ -n "$http_auth" ]; then
	      command="$command -u $http_auth"
    fi

    count=$( eval $command | egrep -o '"count":[0-9]+' | cut -d ":" -f2 )

    # Determine the Nagios Status and Exit Code
    if [ "$count" -gt 10 ]; then
        NAGSTATUS="CRITICAL"
        EXST=$ST_CR
    elif [ "$count" -gt 0 ]; then
        NAGSTATUS="WARNING"
        EXST=$ST_WR
    elif [ "$count" -eq 0 ]; then
        NAGSTATUS="OK"
        EXST=$ST_OK
    else
        NAGSTATUS="UNKNOWN"
        EXST=$ST_UK
    fi
}

do_output() {
get_status
output="elasticsearch ($name) is running. \
watcher count: $count"
}


# Here we go!
which curl >/dev/null 2>&1
if [ "$?" != "0" ]; then
    echo "CRITICAL - curl is not installed"
    exit $ST_CR
fi
which egrep >/dev/null 2>&1
if [ "$?" != "0" ]; then
    echo "CRITICAL - egrep is not installed"
    exit $ST_CR
fi

do_output
       
COMPARE=$listql

echo "${NAGSTATUS} - ${output}"
exit $EXST
